### PR TITLE
Final commit

### PR DESCRIPTION
**Pull request by monstaro**
@ameseee 

Final commit

### CODE REVIEW

**Comment by ameseee** [comment]
Can yall please provide the link to your GH pages? Thanks!

@monstaro @cammac60

**Comment by monstaro** [comment]
Yes! 
https://monstaro.github.io/NumberGuesser/

**Comment by cammac60** [comment]
That link is broken for me, try this one:
https://monstaro.github.io/NumberGuesser/

**Comment by monstaro** [comment]
@cammac60  Thank you - I tried to paste that link through my phone initially and it didn't work.

**Pull request merged**
